### ISSUE TITLE
Encoding problem while installing it with pip3.4

### ISSUE THREAD

**Issue by chickahoona** [django-xxx/django-detect#2]
Hi,

First thanks for that plugin. I currently have some issue while installing it. It looks like the README.rst containing some chars, that throw some ascii decoding error:

```
# pip3 install django-detect
Collecting django-detect
  Downloading django-detect-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5mf2p5y1/django-detect/setup.py", line 13, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 143: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5mf2p5y1/django-detect/
```

We are using python3.4 together with pip3.4.

Best regards
Sascha

**Comment by chickahoona** [comment]
Sorry for this wrong incident. I got this error due to some missing variable (LANG in particular).
